services:
  minimalism-app:
    container_name: minimalism-app
    restart: always
    build:
      dockerfile: Dockerfile.app
    ports:
      - 8082:8080
    environment:
      POCKETBASE_ADRESS: 'http://minimalism-pb:8090'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
