services:
  minimalism-pb:
    image: ghcr.io/muchobien/pocketbase:0.22.20
    container_name: minimalism-pb
    restart: always
    ports:
      - 8090:8090
    environment:
      POCKETBASE_ADRESS: 'http://localhost:8090'
    volumes:
      - ./pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
