services:
  minimalism-app:
    container_name: minimalism-app
    restart: always
    build:
      dockerfile: Dockerfile.app
    ports:
      - 8082:8080
    environment:
      POCKETBASE_ADRESS: 'http://minimalism-pb:8090'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  minimalism-pb:
    container_name: minimalism-pb
    restart: always
    build:
      dockerfile: Dockerfile.pb
    ports:
      - 8090:8090
    volumes:
      - ./pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
