services:
  minimalism-blog:
    container_name: minimalism-blog
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      POCKETBASE_ADRESS: 'https://blog.larsgerber.ch/pb'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
