version: '3'
services:
  app:
    container_name: minimalism-blog
    restart: always
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.node-test-website.rule: "Host(`shargeforce.net`, `www.shargeforce.net`)"
      traefik.http.routers.node-test-website.entrypoints: websecure
      traefik.http.routers.node-test-website.tls: "true"
      traefik.http.routers.node-test-website.tls.certresolver: resolver
      traefik.http.routers.node-test-website.middlewares: security-headers
      traefik.http.routers.node-test-website.tls.options: default
networks:
  default:
    external: true
    name: traefik_default
