version: '3'
services:
  app:
    container_name: minimalism-blog-strapi
    build: .

# docker compose build --no-cache
# then visit https://github.com/larsgerber/minimalism-strapi/blob/master/docker-compose.yml